
// To update these options, run:
// flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// CORRECTED IMPORT: Use the wildcard import to ensure kIsWeb is defined.
import 'package:flutter/foundation.dart'; 


/// Default [FirebaseOptions] for use with your Firebase project.
/// 

/// generated by running the `flutterfire configure` command 
/// in your project root directory!
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for $_platformName - '
          'you can reconfigure this by running the FlutterFire CLI command.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    // DUMMY VALUES: REPLACE WITH YOUR ACTUAL CONFIGURATION
    apiKey: 'AIzaSyBED8W-c5dCfZaLfdyd1vQiDVfaEOlBMFU',
    appId: '1:647381548541:android:658c28aafd9a6525d2ad94',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'cinecmoviebooking', // Use your project ID here
    storageBucket: 'cinecmoviebooking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    // DUMMY VALUES: REPLACE WITH YOUR ACTUAL CONFIGURATION
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:YOUR_IOS_APP_ID:ios:YOUR_IOS_HASH',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'cinecmoviebooking', // Use your project ID here
    storageBucket: 'cinecmoviebooking.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.cinecMovieApp', // Use your actual bundle ID
  );

  static String get _platformName {
    // kIsWeb is now defined due to the foundation.dart import
    if (kIsWeb) {
      return 'Web';
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return 'android';
      case TargetPlatform.iOS:
        return 'ios';
      case TargetPlatform.macOS:
        return 'macos';
      case TargetPlatform.windows:
        return 'windows';
      case TargetPlatform.linux:
        return 'linux';
      default:
        return defaultTargetPlatform.toString();
    }
  }
}
